# Путь к папке с датасетом ВНУТРИ контейнера.
path: /app/data/03_annotated

# Пути к папкам с обучающими и валидационными изображениями
# (относительно параметра 'path' выше)

train: train/images
val: valid/images

# Имена наших классов.
names:
  0: defect