
services:
  detector:
    build: .
    container_name: defect_detector_app
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
      # Связываем том с данными MLflow, чтобы детектор мог сохранять артефакты
      - mlflow-data:/mlflow 
    shm_size: '4g'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Зависит от сервиса mlflow, чтобы он запустился первым
    depends_on:
      - mlflow-server
    command: tail -f /dev/null

  mlflow-server:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    ports:
      - "5001:5000" # Веб-интерфейс будет доступен на http://localhost:5001
    volumes:
      - mlflow-data:/mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri /mlflow
      --default-artifact-root /mlflow
    restart: always

volumes:
  mlflow-data:
    driver: local